[package]
name = "search-rust"
version = "0.1.0"
authors = ["Tiberiu Simion Voicu <tiberiusimionvoicu@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.5.3"
futures = "0.1.17"
hyper = "0.11.13"
log = "0.4.1"
reqwest = "0.9.17"
rouille = "3.0.0"

