apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  progressDeadlineSeconds: 120
  template:
    metadata:
      name: movies
      labels:
        app: movies
    spec:
      hostAliases:
      - ip: "10.0.2.2"
        hostnames:
          - "api.movies.com"
      containers:
      - name: movies
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "256Mi"
        image: movies:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
